id: c39babee-4177-4619-a854-df203a5a9089
full_slug: public-cloud-databases-mirrormaker-capabilities
engine: kafkaMirrorMaker
section: dashboard
reference_category: public-cloud-databases-kafka-mirrormaker-guides