id: dd2cdd7e-8359-4529-9936-acc2f6403a9f
full_slug: public-cloud-databases-postgresql-concept-high-availability
engine: postgresql
section: dashboard
reference_category: public-cloud-databases-postgresql-guides