id: 67af6d6b-900a-40fc-92e6-f5da637cdfc5
full_slug: public-cloud-databases-postgresql-connect-wagtail
engine: postgresql
section: dashboard
reference_category: public-cloud-databases-postgresql-tutorials