id: cc960db1-d187-495a-bcf2-9f3277a8edde
full_slug: public-cloud-databases-postgresql-connect-pgadmin
engine: postgresql
section: dashboard
reference_category: public-cloud-databases-postgresql-guides