id: 0dfb383e-3de9-4f21-b8a9-18cf9e15639b
full_slug: public-cloud-databases-opensearch-getting-started
engine: opensearch
section: dashboard
reference_category: public-cloud-databases-opensearch-guides