id: d56f5080-37df-4852-8a30-f1374b24879a
full_slug: public-cloud-databases-postgresql-connect-strapi
engine: postgresql
section: dashboard
reference_category: public-cloud-databases-postgresql-tutorials