id: 6801a095-9916-49ae-84c3-51077170db85
full_slug: public-cloud-private-registry-scan-docker-images-vulnerabilities
reference_category: public-cloud-containers-orchestration-managed-private-registry-tutorials