id: eb5a9307-c6f4-4324-bd49-414824232ce8
full_slug: public-cloud-kubernetes-automatically-label-taint-node-pool
reference_category: public-cloud-containers-orchestration-managed-kubernetes-k8s-tutorials