id: b1b63859-8ae8-40ba-8413-ceb7e000e3ca
full_slug: public-cloud-private-registry-deploy-chart-from-kubernetes-registry
reference_category: public-cloud-containers-orchestration-managed-private-registry-tutorials