id: 84e4410d-257c-49b7-a31a-d38e4ecc7466
full_slug: public-cloud-kubernetes-getting-source-ip-behind-loadbalancer
reference_category: public-cloud-containers-orchestration-managed-kubernetes-k8s-tutorials