id: f8f9ecd0-be1c-4bd3-ab58-25599446ea2e
full_slug: public-cloud-private-registry-configure-oidc-provider-authentication
reference_category: public-cloud-containers-orchestration-managed-private-registry-tutorials