id: f40c2036-64b7-4390-9247-695f9c3add87
full_slug: public-cloud-databases-kafkaconnect-advanced-parameters-references
engine: kafkaConnect
section: settings
reference_category: public-cloud-databases-kafka-connect-guides