id: 6e3ff09a-ad11-11ed-afa1-0242ac120002
full_slug: public-cloud-databases-postgresql-terminate-queries
engine: postgresql
section: queries
reference_category: public-cloud-databases-postgresql-guides