id: 242280ec-1e33-4ff3-becf-41091d22c4d5
full_slug: public-cloud-databases-postgresql-configure-instance
engine: postgresql
section: settings
reference_category: public-cloud-databases-postgresql-guides