id: 84965be7-43de-4479-88d4-d6a62a6845ad
full_slug: public-cloud-private-registry-sign-artifacts-with-cosign
reference_category: public-cloud-containers-orchestration-managed-private-registry-tutorials