id: ca3a246b-42da-4cc8-a4eb-afbfc13aab39
full_slug: public-cloud-databases-kafkaconnect-capabilities
engine: kafkaConnect
section: dashboard
reference_category: public-cloud-databases-kafka-connect-guides